lpc_py_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('auth', obtain_auth_token),
    path('teams/', include('teams.urls')),
    path('matches/', include('match.urls')),
    path('league/', include('league.urls')),
    path('apiLeague/', include('leagueApi.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
]

match/urls.py
from django.urls import path
from . import views


app_name = 'match'

urlpatterns = [
    path('', views.AllMatchesToPlayListView.as_view(), name='all_matches'),
    path('played', views.AllMatchesPlayedListView.as_view(), name='all_matches_played'),
    path('my_matches/', views.MyMatchesToPlayListView.as_view(), name='my_matches'),
    path('my_matches/played',views. MyMatchesPlayedListView.as_view(), name='my_matches_played'),
    path('close/<int:match_id>/', views.close_match, name='close_match'),
]

teams/urls.py
from django.urls import path
from . import views

app_name = 'teams'

urlpatterns = [
    path('index/', views.index_test, name='index_test'),
    path('', views.AllTeamListView.as_view(), name='all_teams'),
    path('all_ready_teams/', views.AllReadyTeamListView.as_view(), name='all_ready_teams'),
    path('<int:pk>/', views.AllTeamDetail.as_view(), name='all_team_detail'),
    path('my_teams/', views.MyTeamsListView.as_view(), name='my_teams'),
    path('my_retired_teams/', views.MyRetiredTeamsListView.as_view(), name='my_retired_teams'),
    path('my_teams/create', views.get_create_my_team, name='create_my_team'),
    path('my_teams/dismiss/<int:pk>/', views.dismiss_team, name='dismiss_team'),
    path('my_teams/preapre/<int:pk>/', views.prepare_team, name='prepare_team'),
    path('my_teams/ready/<int:pk>/', views.ready_team, name='ready_team'),
    path('my_teams/buy_player/<int:team_id>', views.buy_player, name='buy_player'),
    path('my_teams/fire_player/<int:team_id>', views.fire_player, name='fire_player'),
    path('my_teams/detail/<int:team_id>', views.my_team_detail, name='my_team_detail'),
    path('my_teams/buy_re_roll/<int:team_id>', views.buy_re_roll, name='buy_re_roll'),
    path('my_teams/remove_re_roll/<int:team_id>', views.remove_re_roll, name='remove_re_roll'),
    path('my_teams/buy_assistant_coach/<int:team_id>', views.buy_assistant_coach, name='buy_assistant_coach'),
    path('my_teams/remove_assistant_coach/<int:team_id>', views.remove_assistant_coach, name='remove_assistant_coach'),
    path('my_teams/buy_cheerleader/<int:team_id>', views.buy_cheerleader, name='buy_cheerleader'),
    path('my_teams/remove_cheerleader/<int:team_id>', views.remove_cheerleader, name='remove_cheerleader'),
    path('my_teams/buy_extra_fan/<int:team_id>', views.buy_extra_fan, name='buy_extra_fan'),
    path('my_teams/remove_extra_fan/<int:team_id>', views.remove_extra_fan, name='remove_extra_fan'),
    path('my_teams/buy_apothecary/<int:team_id>', views.buy_apothecary, name='buy_apothecary'),
    path('my_teams/remove_apothecary/<int:team_id>', views.remove_apothecary, name='remove_apothecary'),
    path('my_teams/manage_player/<int:team_id>', views.manage_player, name='manage_player'),
    path('my_teams/manage_player/change_name_number', views.change_player_name_number, name='change_player_name_number'),
    path('my_teams/manage_player/fire_player/<int:team_id>', views.manage_fire_player, name='manage_fire_player'),

    path('my_teams/manage_team/buy_re_roll/<int:team_id>', views.manage_buy_re_roll, name='manage_buy_re_roll'),
    path('my_teams/manage_team/remove_re_roll/<int:team_id>', views.manage_remove_re_roll, name='manage_remove_re_roll'),
    path('my_teams/manage_team/buy_assistant_coach/<int:team_id>', views.manage_buy_assistant_coach,
         name='manage_buy_assistant_coach'),
    path('my_teams/manage_team/remove_assistant_coach/<int:team_id>', views.manage_remove_assistant_coach,
         name='manage_remove_assistant_coach'),
    path('my_teams/manage_team/buy_cheerleader/<int:team_id>', views.manage_buy_cheerleader, name='manage_buy_cheerleader'),
    path('my_teams/manage_team/remove_cheerleader/<int:team_id>', views.manage_remove_cheerleader,
         name='manage_remove_cheerleader'),
    path('my_teams/manage_team/buy_apothecary/<int:team_id>', views.manage_buy_apothecary, name='manage_buy_apothecary'),
    path('my_teams/manage_team/remove_apothecary/<int:team_id>', views.manage_remove_apothecary,
         name='manage_remove_apothecary'),
    path('my_teams/manage_team/buy_player.py/<int:team_id>', views.manage_buy_player, name='manage_buy_player'),
    path('my_teams/manage_team/levelup/<int:player_id>', views.player_level_up, name='player_level_up'),
    path('my_teams/manage_team/levelup/first_random/<int:player_id>', views.random_first_skill, name='random_first_skill'),
    path('my_teams/manage_team/levelup/second_random/<int:player_id>', views.random_second_skill, name='random_second_skill'),
    path('my_teams/manage_team/levelup/choose_first/<int:player_id>', views.select_first_skill, name='select_first_skill'),
    path('my_teams/manage_team/levelup/choose_secondary/<int:player_id>', views.select_second_skill,
         name='select_second_skill'),
    path('my_teams/create_pdf/<int:team_id>', views.render_pdf_view, name='create_pdf'),
    path('my_teams/manage_team/confirm_journeyman/<int:team_id>', views.confirm_journeyman, name='confirm_journeyman')
]

match/forms.py
from django import forms

match/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction
from django.db.models import Q
from django.http import HttpResponse
from django.utils.decorators import method_decorator
from django.views.generic import ListView
from match.models import Match
from django.shortcuts import render, redirect, get_object_or_404
from teams.team_helper import update_team_value
from .close_helpers.tournament_helper import update_tournament_result
from .match_container import MatchContainer
from .match_util import CloseMatchDataReader, reset_missing_next_game, is_conceded
from django.contrib import messages
import logging

logger = logging.getLogger(__name__)


# Create your views here.
class AllMatchesToPlayListView(LoginRequiredMixin, ListView):
    model = Match
    template_name = 'matches/all_matches.html'
    context_object_name = 'matches'
    paginate_by = 20

    def get_queryset(self):
        return Match.objects.filter(played=False).order_by('-match_date_from')

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(AllMatchesToPlayListView, self).dispatch(request, args, kwargs)


class AllMatchesPlayedListView(LoginRequiredMixin, ListView):
    model = Match
    template_name = 'matches/all_matches_played.html'
    context_object_name = 'matches'
    paginate_by = 20

    def get_queryset(self):
        return Match.objects.filter(played=True).order_by('-match_date_from')

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(AllMatchesPlayedListView, self).dispatch(request, args, kwargs)


class MyMatchesToPlayListView(LoginRequiredMixin, ListView):
    model = Match
    template_name = 'matches/my_matches.html'
    context_object_name = 'matches'
    paginate_by = 20

    def get_queryset(self):
        return Match.objects.filter(
            (Q(first_team__coach=self.request.user) | Q(second_team__coach=self.request.user)) & Q(played=False)
        ).order_by('-match_date_from')

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(MyMatchesToPlayListView, self).dispatch(request, args, kwargs)


class MyMatchesPlayedListView(LoginRequiredMixin, ListView):
    model = Match
    template_name = 'matches/my_matches_played.html'
    context_object_name = 'matches'
    paginate_by = 20

    def get_queryset(self):
        return Match.objects.filter(
            (Q(first_team__coach=self.request.user) | Q(second_team__coach=self.request.user)) & Q(played=True)
        ).order_by('-match_date_from')

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(MyMatchesPlayedListView, self).dispatch(request, args, kwargs)


@login_required
def close_match(request, *args, **kwargs):
    match_id = kwargs.get('match_id')
    logger.debug('User ' + str(request.user) + ' Try to close match ')
    if not request.user.is_superuser:
        logger.warning('User ' + str(request.user) + ' is not an admin ')
        return HttpResponse(status=403)  # HTTP 403 Forbidden

    match = get_object_or_404(Match, id=match_id)

    logger.debug('User ' + str(request.user) + ' close match ' + match.debug())

    if request.method == 'POST':
        data = request.POST
        logger.debug('User ' + str(request.user) + ' form data ' + str(data))

        # FIRST CHECK IF THERE IS CONCEDED. TODO: Rewrite all concede code
        conceded, conceded_error, conceded_data = is_conceded(data)
        if conceded_error:
            messages.error(request, conceded_data)
            first_team_players = match.first_team.players.all()
            second_team_players = match.second_team.players.all()
            first_team_dedicated_fan = match.first_team.extra_dedicated_fan + 1
            second_team_dedicated_fan = match.second_team.extra_dedicated_fan + 1
            return render(request, 'matches/close_match.html',
                          {'match': match, 'first_team_players': first_team_players,
                           'second_team_players': second_team_players,
                           'first_team_dedicated_fan': first_team_dedicated_fan,
                           'second_team_dedicated_fan': second_team_dedicated_fan})

        try:
            with transaction.atomic():

                # Reset the MNG flag. First things otherwise we reset the MNG due close match
                reset_missing_next_game(match.first_team)
                reset_missing_next_game(match.second_team)

                match_data = CloseMatchDataReader(data, match, conceded_data)

                match_data.prepare()
                match_data.post_match()
                match_data.winning_points()

                first_team_fan_update = data.get("first_team_update_fan")
                if first_team_fan_update:
                    match.first_team.extra_dedicated_fan += int(first_team_fan_update)
                    logger.debug('For match ' + str(match) + ' first team update team fan ' + first_team_fan_update)
                    if match.first_team.extra_dedicated_fan < 0:
                        match.first_team.extra_dedicated_fan = 0

                second_team_fan_update = data.get("second_team_update_fan")
                if second_team_fan_update:
                    match.second_team.extra_dedicated_fan += int(second_team_fan_update)
                    logger.debug('For match ' + str(match) + ' second team update team fan ' + second_team_fan_update)
                    if match.second_team.extra_dedicated_fan < 0:
                        match.second_team.extra_dedicated_fan = 0

                match.first_team.value = update_team_value(match.first_team, True)
                match.first_team.current_team_value = update_team_value(match.first_team)
                logger.debug('For match ' + str(match) + ' first team TV ' + str(match.first_team.value)
                             + ' current value ' + str(match.first_team.current_team_value))

                match.second_team.value = update_team_value(match.second_team, True)
                match.second_team.current_team_value = update_team_value(match.second_team)
                logger.debug('For match ' + str(match) + ' second team TV ' + str(match.second_team.value)
                             + ' current value ' + str(match.second_team.current_team_value))

                # first_team_extra_td = data["first_team_extra_td"]
                # second_team_extra_td = data["second_team_extra_td"]

                # if first_team_extra_td:
                #    first_team_extra_td_int = int(first_team_extra_td)
                #    match.first_team_td += first_team_extra_td_int
                #    match.first_team.total_touchdown += first_team_extra_td_int

                # if second_team_extra_td:
                #    second_team_extra_td_int = int(second_team_extra_td)
                #    match.second_team_td += second_team_extra_td_int
                #    match.second_team.total_touchdown += second_team_extra_td_int

                first_team_gold = data.get('first_team_gold')
                second_team_gold = data.get('second_team_gold')

                if first_team_gold:
                    first_team_gold_int = int(first_team_gold)
                    match.first_team_gold = first_team_gold_int
                    logger.debug('For match ' + str(match) + ' team ' + str(match.first_team)
                                 + ' add gold ' + first_team_gold)
                    match.first_team.treasury += first_team_gold_int

                if second_team_gold:
                    second_team_gold_int = int(second_team_gold)
                    match.second_team_gold = second_team_gold_int
                    logger.debug('For match ' + str(match) + ' team ' + str(match.second_team)
                                 + ' add gold ' + second_team_gold)
                    match.second_team.treasury += second_team_gold_int

                # Reset freeze status
                logger.debug(f"Reset freeze status for {str(match.first_team)} and {str(match.second_team)}")
                match.first_team.freeze = False
                match.second_team.freeze = False

                match.first_team.save()
                match.second_team.save()
                match.played = True
                match.save()

                # match_container = MatchContainer(match)

                # UPDATE TOURNAMENT RESULT
                if match.tournament is not None:
                    update_tournament_result(match, match_data)

                logger.debug('User ' + str(request.user) + ' closed match ' + match.debug())

        except Exception as e:
            logger.error('User ' + str(request.user) + ' close match Exception ' + str(e))
            messages.error(request, 'Internal error in close match Player')

        return redirect('match:all_matches')
    else:
        first_team_players = match.first_team.players.all()
        second_team_players = match.second_team.players.all()
        first_team_dedicated_fan = match.first_team.extra_dedicated_fan + 1
        second_team_dedicated_fan = match.second_team.extra_dedicated_fan + 1
        return render(request, 'matches/close_match.html', {'match': match, 'first_team_players': first_team_players,
                                                            'second_team_players': second_team_players,
                                                            'first_team_dedicated_fan': first_team_dedicated_fan,
                                                            'second_team_dedicated_fan': second_team_dedicated_fan})

templates/matches/all_matches.html
{% extends 'base.html' %}

{% block title %}All Matches{% endblock %}

{% block content %}

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">All matches to play</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable">
                    <thead>
                    <tr>
                        <th>Team A</th>
                        <th>Team B</th>
                        <th>From Date</th>
                        <th>to Date</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for obj in matches %}
                        <tr>
                            <td>
                                <a href="{% url 'teams:my_team_detail' obj.first_team.id %}">
                                    {{ obj.first_team }}
                                </a>
                                - [CTV {{ obj.first_team.current_team_value }}]
                            </td>
                            <td>
                                <a href="{% url 'teams:my_team_detail' obj.second_team.id %}">
                                    {{ obj.second_team }}
                                </a>
                                - [CTV {{ obj.second_team.current_team_value }}]
                            </td>
                            <td>{{ obj.match_date_from }}</td>
                            <td>{{ obj.match_date_to }}</td>
                            <td>
                                {% if user.is_superuser %}
                                    <a href="{% url 'match:close_match' obj.id %}" class="btn btn-primary">CLOSE</a>
                                {% else %}
                                    <b>NO ACTION</b>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <br>
    <!-- {% include "pagination.html" with page=page_obj %} -->
{% endblock %}

templates/matches/all_matches_played.html
{% extends 'base.html' %}

{% block title %}All Matches{% endblock %}

{% block content %}


    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">All matches played</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable">
                    <thead>
                    <tr>
                        <th>Team A</th>
                        <th>Team B</th>
                        <th>Date</th>
                        <th>Team A TD</th>
                        <th>Team B TD</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for obj in matches %}
                        <tr>
                            <td>{{ obj.first_team }}</td>
                            <td>{{ obj.second_team }}</td>
                            <td>{{ obj.match_date_from }} - {{ obj.match_date_to }}</td>
                            <td>{{ obj.first_team_td }}</td>
                            <td>{{ obj.second_team_td }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <!-- {% include "pagination.html" with page=page_obj %} -->
{% endblock %}

templates/matches/my_matches.html
{% extends 'base.html' %}

{% block title %}My Matches{% endblock %}

{% block content %}

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">My matches</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable">
                    <thead>
                    <tr>
                        <th>Team A</th>
                        <th>Team B</th>
                        <th>From Date</th>
                        <th>To Date</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for obj in matches %}
                        <tr>
                            <td>
                                <a href="{% url 'teams:all_team_detail' obj.first_team.id %}">{{ obj.first_team }}</a>
                                - [CTV {{ obj.first_team.current_team_value }}]
                            </td>
                            <td>
                                <a href="{% url 'teams:all_team_detail' obj.second_team.id %}">{{ obj.second_team }}</a>
                                - [CTV {{ obj.second_team.current_team_value }}]
                            </td>
                            <td>{{ obj.match_date_from }}</td>
                            <td>{{ obj.match_date_to }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <br>
    <!-- {% include "pagination.html" with page=page_obj %} -->
{% endblock %}

templates/matches/my_matches_played.html
{% extends 'base.html' %}

{% block title %}My Matches{% endblock %}

{% block content %}

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">My played matches</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable">
                    <thead>
                    <tr>
                        <th>Team A</th>
                        <th>Team B</th>
                        <th>Date</th>
                        <th>Team A TD</th>
                        <th>Team B TD</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for obj in matches %}
                        <tr>
                            <td>{{ obj.first_team }}</td>
                            <td>{{ obj.second_team }}</td>
                            <td>{{ obj.match_date_from }} - {{ obj.match_date_to }}</td>
                            <td>{{ obj.first_team_td }}</td>
                            <td>{{ obj.second_team_td }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <br>
    <!-- {% include "pagination.html" with page=page_obj %} -->
{% endblock %}