lpc_py_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('auth', obtain_auth_token),
    path('teams/', include('teams.urls')),
    path('matches/', include('match.urls')),
    path('league/', include('league.urls')),
    path('apiLeague/', include('leagueApi.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
]

match/urls.py
from django.urls import path
from . import views


app_name = 'match'

urlpatterns = [
    path('', views.AllMatchesToPlayListView.as_view(), name='all_matches'),
    path('played', views.AllMatchesPlayedListView.as_view(), name='all_matches_played'),
    path('my_matches/', views.MyMatchesToPlayListView.as_view(), name='my_matches'),
    path('my_matches/played',views. MyMatchesPlayedListView.as_view(), name='my_matches_played'),
    path('close/<int:match_id>/', views.close_match, name='close_match'),
]

teams/urls.py
from django.urls import path
from . import views

app_name = 'teams'

urlpatterns = [
    path('index/', views.index_test, name='index_test'),
    path('', views.AllTeamListView.as_view(), name='all_teams'),
    path('all_ready_teams/', views.AllReadyTeamListView.as_view(), name='all_ready_teams'),
    path('<int:pk>/', views.AllTeamDetail.as_view(), name='all_team_detail'),
    path('my_teams/', views.MyTeamsListView.as_view(), name='my_teams'),
    path('my_retired_teams/', views.MyRetiredTeamsListView.as_view(), name='my_retired_teams'),
    path('my_teams/create', views.get_create_my_team, name='create_my_team'),
    path('my_teams/dismiss/<int:pk>/', views.dismiss_team, name='dismiss_team'),
    path('my_teams/preapre/<int:pk>/', views.prepare_team, name='prepare_team'),
    path('my_teams/ready/<int:pk>/', views.ready_team, name='ready_team'),
    path('my_teams/buy_player/<int:team_id>', views.buy_player, name='buy_player'),
    path('my_teams/fire_player/<int:team_id>', views.fire_player, name='fire_player'),
    path('my_teams/detail/<int:team_id>', views.my_team_detail, name='my_team_detail'),
    path('my_teams/buy_re_roll/<int:team_id>', views.buy_re_roll, name='buy_re_roll'),
    path('my_teams/remove_re_roll/<int:team_id>', views.remove_re_roll, name='remove_re_roll'),
    path('my_teams/buy_assistant_coach/<int:team_id>', views.buy_assistant_coach, name='buy_assistant_coach'),
    path('my_teams/remove_assistant_coach/<int:team_id>', views.remove_assistant_coach, name='remove_assistant_coach'),
    path('my_teams/buy_cheerleader/<int:team_id>', views.buy_cheerleader, name='buy_cheerleader'),
    path('my_teams/remove_cheerleader/<int:team_id>', views.remove_cheerleader, name='remove_cheerleader'),
    path('my_teams/buy_extra_fan/<int:team_id>', views.buy_extra_fan, name='buy_extra_fan'),
    path('my_teams/remove_extra_fan/<int:team_id>', views.remove_extra_fan, name='remove_extra_fan'),
    path('my_teams/buy_apothecary/<int:team_id>', views.buy_apothecary, name='buy_apothecary'),
    path('my_teams/remove_apothecary/<int:team_id>', views.remove_apothecary, name='remove_apothecary'),
    path('my_teams/manage_player/<int:team_id>', views.manage_player, name='manage_player'),
    path('my_teams/manage_player/change_name_number', views.change_player_name_number, name='change_player_name_number'),
    path('my_teams/manage_player/fire_player/<int:team_id>', views.manage_fire_player, name='manage_fire_player'),

    path('my_teams/manage_team/buy_re_roll/<int:team_id>', views.manage_buy_re_roll, name='manage_buy_re_roll'),
    path('my_teams/manage_team/remove_re_roll/<int:team_id>', views.manage_remove_re_roll, name='manage_remove_re_roll'),
    path('my_teams/manage_team/buy_assistant_coach/<int:team_id>', views.manage_buy_assistant_coach,
         name='manage_buy_assistant_coach'),
    path('my_teams/manage_team/remove_assistant_coach/<int:team_id>', views.manage_remove_assistant_coach,
         name='manage_remove_assistant_coach'),
    path('my_teams/manage_team/buy_cheerleader/<int:team_id>', views.manage_buy_cheerleader, name='manage_buy_cheerleader'),
    path('my_teams/manage_team/remove_cheerleader/<int:team_id>', views.manage_remove_cheerleader,
         name='manage_remove_cheerleader'),
    path('my_teams/manage_team/buy_apothecary/<int:team_id>', views.manage_buy_apothecary, name='manage_buy_apothecary'),
    path('my_teams/manage_team/remove_apothecary/<int:team_id>', views.manage_remove_apothecary,
         name='manage_remove_apothecary'),
    path('my_teams/manage_team/buy_player.py/<int:team_id>', views.manage_buy_player, name='manage_buy_player'),
    path('my_teams/manage_team/levelup/<int:player_id>', views.player_level_up, name='player_level_up'),
    path('my_teams/manage_team/levelup/first_random/<int:player_id>', views.random_first_skill, name='random_first_skill'),
    path('my_teams/manage_team/levelup/second_random/<int:player_id>', views.random_second_skill, name='random_second_skill'),
    path('my_teams/manage_team/levelup/choose_first/<int:player_id>', views.select_first_skill, name='select_first_skill'),
    path('my_teams/manage_team/levelup/choose_secondary/<int:player_id>', views.select_second_skill,
         name='select_second_skill'),
    path('my_teams/create_pdf/<int:team_id>', views.render_pdf_view, name='create_pdf'),
    path('my_teams/manage_team/confirm_journeyman/<int:team_id>', views.confirm_journeyman, name='confirm_journeyman')
]

teams/forms.py
from django import forms


class CreateMyTeamForm(forms.Form):
    name = forms.CharField(max_length=100)
    treasury = forms.IntegerField(min_value=0, max_value=2000000)
    roster = forms.ChoiceField()


class RandomSkill(forms.Form):
    CATEGORY_CHOICE = (
        ('a', 'AGILITY'),
        ('g', 'GENERAL'),
        ('m', 'MUTATION'),
        ('p', 'PASSING'),
        ('s', 'STRENGTH'),
    )
    category = forms.ChoiceField(choices=CATEGORY_CHOICE)
    first_dice = forms.IntegerField(min_value=1, max_value=6)
    second_dice = forms.IntegerField(min_value=1, max_value=6)

teams/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.template.loader import get_template
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.generic import ListView, DetailView
from xhtml2pdf import pisa

from league.models import Tournament, TournamentTeamResult
from lpc_py_manager.security_util import is_team_belong_to_logged_user, is_roster_player_belongs_to_roster, \
    is_player_belongs_to_team, is_team_in_league_i_manage
from .buy_fire_helpers.buy_journeyman import BuyJourneyman
from .models import Team, TeamPlayer
from .forms import CreateMyTeamForm, RandomSkill
from roster.models import RosterTeam, RosterPlayer, Skill, Trait
from django.contrib import messages
from .team_helper import update_team_value, perform_dismiss_team, perform_ready_team, is_players_count_to_prepare_team, \
    can_you_buy_player, add_re_roll_during_team_prepare, remove_re_roll_during_team_prepare, \
    add_assistant_coach_during_team_prepare, remove_assistant_coach_during_team_prepare, \
    add_cheerleader_during_team_prepare, remove_cheerleader_during_team_prepare, add_extra_fan_during_team_prepare, \
    remove_extra_fan_during_team_prepare, add_apothecary_during_team_prepare, remove_apothecary_during_team_prepare, \
    change_player_name_number_by_request, buy_team_re_roll, remove_team_re_roll, buy_team_assistant_coach, \
    remove_team_assistant_coach, buy_team_cheerleader, remove_team_cheerleader, buy_team_apothecary, \
    remove_team_apothecary, get_random_skill_search_string, update_team_freeze, fire_player_helper
from django.db.models import Q
from .levelup_helper import get_levelup_cost_by_level, get_levelup_cost_all_levels, get_first_skills_category, \
    get_new_level, get_second_skills_category, get_first_skills_select_option, get_second_skills_select_option
import logging
from .buy_fire_helpers.buy_player import BuyPlayer

logger = logging.getLogger(__name__)


# Create your views here.
class AllTeamListView(ListView):
    model = Team
    template_name = 'teams/all_teams.html'
    context_object_name = 'teams'
    paginate_by = 20
    ordering = ['-name']

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(AllTeamListView, self).dispatch(request, args, kwargs)


class AllReadyTeamListView(ListView):
    model = Team
    template_name = 'teams/all_teams.html'
    context_object_name = 'teams'
    paginate_by = 20
    ordering = ['-name']

    def get_queryset(self):
        return Team.objects.filter(
            Q(status='READY')
        ).order_by('name')

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(AllReadyTeamListView, self).dispatch(request, args, kwargs)


class AllTeamDetail(DetailView):
    model = Team
    template_name = 'teams/all_team_detail.html'
    context_object_name = 'team'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        self.request = request
        return super(AllTeamDetail, self).dispatch(request, args, kwargs)

    def get_context_data(self, **kwargs):
        context = super(AllTeamDetail, self).get_context_data(**kwargs)
        team = context['team']
        dedicated_fan = getattr(team, 'extra_dedicated_fan')
        enable_edit = is_team_in_league_i_manage(team, self.request)

        logger.debug(f"All team details for team {team} - Dedicated fan => {dedicated_fan} - Enable edit {enable_edit}")

        context['dedicated_fan'] = dedicated_fan + 1
        context['enable_edit'] = enable_edit
        return context


class MyTeamsListView(LoginRequiredMixin, ListView):
    model = Team
    template_name = 'teams/my_teams.html'
    context_object_name = 'teams'
    paginate_by = 20

    def get_queryset(self):
        return Team.objects.filter(
            (Q(coach=self.request.user) & ~Q(status='RETIRED'))
        ).order_by('name')

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(MyTeamsListView, self).dispatch(request, args, kwargs)


class MyRetiredTeamsListView(LoginRequiredMixin, ListView):
    model = Team
    template_name = 'teams/my_teams.html'
    context_object_name = 'teams'
    paginate_by = 20

    def get_queryset(self):
        return Team.objects.filter(
            (Q(coach=self.request.user) & Q(status='RETIRED'))
        ).order_by('name')

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(MyRetiredTeamsListView, self).dispatch(request, args, kwargs)


@login_required
def get_create_my_team(request):
    logger.debug('User ' + str(request.user) + ' made a create team request with method ' + request.method)

    roster_teams = RosterTeam.objects.all()
    team = tuple((t.id, t.name) for t in roster_teams)
    if request.method == 'POST':
        form = CreateMyTeamForm(request.POST)
        form.fields['roster'].choices = team

        logger.debug('Create team POST. Roster choice ' + str(team))
        logger.debug('Create team POST. Data sent ' + str(request.POST))

        if form.is_valid():
            name = form.cleaned_data['name']
            treasury = form.cleaned_data['treasury']
            roster = form.cleaned_data['roster']
            created_team = Team(name=name, treasury=treasury, roster_team_id=roster, coach=request.user,
                                status='CREATED')
            logger.debug('Create team POST. Form valid. Create team ' + str(created_team))
            created_team.save()
            return redirect('teams:my_teams')
        else:
            messages.error(request, form.errors)
            form = CreateMyTeamForm()
            form.fields['roster'].choices = team
            logger.warning('Create team POST. Form invalid ' + str(form.errors))
            return render(request, 'teams/createMyTeam.html', {'form': form})
    else:
        form = CreateMyTeamForm()
        form.fields['roster'].choices = team
        logger.debug('Create team GET. Return form with this roster choice ' + str(team))
        return render(request, 'teams/createMyTeam.html', {'form': form})


@login_required
def dismiss_team(request, *args, **kwargs):
    pk = kwargs.get('pk')
    team = get_object_or_404(Team, id=pk)
    logger.debug('User ' + str(request.user) + ' try to dismiss team ' + str(team))
    if not is_team_belong_to_logged_user(team, request):
        messages.error(request, 'You cannot retire a team not belongs to you')
    else:
        perform_dismiss_team(team, request)
        messages.success(request, 'You retire ' + str(team))
    return redirect('teams:my_teams')


@login_required
def prepare_team(request, *args, **kwargs):
    pk = kwargs.get('pk')
    team = get_object_or_404(Team, id=pk)
    logger.debug('User ' + str(request.user) + ' try to prepare team ' + str(team))
    roster_players = team.roster_team.roster_players.filter(is_journeyman=False).all()

    if not is_team_belong_to_logged_user(team, request):
        messages.error(request, 'You cannot prepare a team not belongs to you')
        return redirect('teams:my_teams')

    return render(request,
                  'teams/prepare_team.html', {'team': team, 'roster_players': roster_players})


@login_required
def ready_team(request, *args, **kwargs):
    pk = kwargs.get('pk')
    team = get_object_or_404(Team, id=pk)

    if not is_team_belong_to_logged_user(team, request):
        messages.error(request, 'You cannot ready a team not belongs to you')
    elif not is_players_count_to_prepare_team(team, request):
        messages.error(request, 'A team must have 11 to 16 players. You cannot ready a not complete team')
    else:
        perform_ready_team(team, request)
    return redirect('teams:my_teams')


@login_required
def buy_player(request, *args, **kwargs):
    team_id = kwargs.get('team_id')
    # You can buy only player not journeyman. The J didn't show into the list of players. But add a check
    roster_player_id = request.GET.get('roster_player', None)
    team = get_object_or_404(Team, id=team_id)
    roster_player_to_buy = get_object_or_404(RosterPlayer, id=roster_player_id)
    kwargs = {'pk': team.id}

    logger.debug('User ' + str(request.user) + ' try to buy ' + str(roster_player_to_buy) + ' for team '
                 + str(team))

    if not is_team_belong_to_logged_user(team, request):
        messages.error(request, 'You cannot buy a player for a team not belongs to you')
        return redirect('teams:prepare_team', **kwargs)

    if roster_player_to_buy.is_journeyman:
        messages.error(request, 'You cannot buy a Journeyman player during team preparation')
        logger.warning('User ' + str(request.user) + ' try to buy a journeyman ' + str(roster_player_to_buy)
                       + ' for team ' + str(team))
        return redirect('teams:prepare_team', **kwargs)

    is_buy_valid = True

    # Check if roster_player_id belongs to roster team
    if not is_roster_player_belongs_to_roster(team, roster_player_id, request.user):
        messages.error(request, 'You cannot buy that player because it is not belong with the chosen roster')
        return redirect('teams:my_teams')

    is_buy_valid = can_you_buy_player(team, request, roster_player_to_buy)

    if is_buy_valid:
        player = TeamPlayer()
        player.init_with_roster_player(roster_player_to_buy, team)
        team.treasury = team.treasury - roster_player_to_buy.cost
        if roster_player_to_buy.big_guy:
            team.big_guy_numbers += 1
        team.number_of_players += 1

        try:
            with transaction.atomic():
                team.save()
                player.save()

templates/teams/levelup.html
{% extends 'base.html' %}

{% block title %}Levelup Player{% endblock %}

{% block content %}

    <h1>Level up <b>{{ player.name }}</b></h1>
    <br>
    <hr>
    <!-- PLayer summary row -->
    <div class="row">
        <div class="col-xl-12 col-md-6 mb-4">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h3 class="m-0 font-weight-bold text-primary">Player Details</h3>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable">
                            <thead>
                            <th>POSITION</th>
                            <TH>MA</TH>
                            <TH>ST</TH>
                            <TH>AG</TH>
                            <TH>PA</TH>
                            <TH>AV</TH>
                            <TH>SKILLS & TRAITS</TH>
                            <TH>Current Value</TH>
                            <TH>SPP</TH>
                            <TH>Level</TH>
                            </thead>
                            <tbody>
                            <tr>
                                <td>{{ player.position }}</td>
                                <td>{{ player.movement_allowance }}</td>
                                <td>{{ player.strength }}</td>
                                <td>{{ player.agility }}</td>
                                <td>
                                    {% if player.passing != 0 %}
                                        {{ player.passing }}+
                                    {% else %}
                                        -
                                    {% endif %}
                                </td>
                                <td>{{ player.armor_value }}</td>
                                <td>
                                    {% for skill in player.base_skills.all %}
                                        {{ skill.name }},
                                    {% endfor %}
                                    {% for trait in player.traits.all %}
                                        {{ trait.name }},
                                    {% endfor %}
                                    {% for skill in player.extra_skills.all %}
                                        {{ skill.name }},
                                    {% endfor %}
                                </td>
                                <td>{{ player.value }}</td>
                                <td>{{ player.spp }}</td>
                                <td>{{ player.level }}</td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Upgrade possibility -->
    <div class="row">
        <!-- Random Card -->
        <div class="col-xl-2 col-md-6 mb-4">
            <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                Oh no!!!
                            </div>
                            <br>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">
                                Your not ready to level up?
                            </div>
                            <br>
                            <Br>
                            <br>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">
                                <a href="{{ player.team.get_my_team_detail_absolute_url }}"
                                   class="btn btn-primary">GO BACK</a>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Random Card -->
        <div class="col-xl-2 col-md-6 mb-4">
            <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                Randomly Select a Primary Skill
                            </div>
                            <br>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">
                                You can spend {{ level_cost.0 }} to obtain a random skill
                            </div>
                            <br>
                            <Br>
                            <br>
                            {% if player.spp >= level_cost.0 %}
                                <div class="h5 mb-0 font-weight-bold text-gray-800">
                                    <a href="{% url 'teams:random_first_skill' player.id %}"
                                       class="btn btn-primary">GET THIS LEVELUP</a>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- First skill Card -->
        <div class="col-xl-2 col-md-6 mb-4">
            <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                Select a Primary Skill
                            </div>
                            <br>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">
                                Spend {{ level_cost.1 }} to choose a primary skill
                            </div>
                            <br>
                            {% if player.spp >= level_cost.1 %}
                                <div class="h5 mb-0 font-weight-bold text-gray-800">
                                    <a href="{% url 'teams:select_first_skill' player.id %}" class="btn btn-primary">GET THIS LEVELUP</a>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Random second skill Card -->
        <div class="col-xl-2 col-md-6 mb-4">
            <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                Select a random on secondary skill
                            </div>
                            <br>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">
                                Spend {{ level_cost.1 }} to choose a randomly Secondary Skill
                            </div>
                            <br>
                            {% if player.spp >= level_cost.1 %}
                                <div class="h5 mb-0 font-weight-bold text-gray-800">
                                    <a href="{% url 'teams:random_second_skill' player.id %}" class="btn btn-primary">GET THIS LEVELUP</a>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Second Skill Card -->
        <div class="col-xl-2 col-md-6 mb-4">
            <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                Select a Secondary Skill
                            </div>
                            <br>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">
                                You can spend {{ level_cost.2 }} to choose a secondary Skill
                            </div>
                            <br>
                            <Br>
                            <br>
                            {% if player.spp >= level_cost.2 %}
                                <div class="h5 mb-0 font-weight-bold text-gray-800">
                                    <a href="{% url 'teams:select_second_skill' player.id %}" class="btn btn-primary">GET THIS LEVELUP</a>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Improve char Card -->
        <div class="col-xl-2 col-md-6 mb-4">
            <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                Randomly characteristic improvement
                            </div>
                            <br>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">
                                You can spend {{ level_cost.3 }} to randomly improve a characteristic
                            </div>
                            <br>
                            <Br>
                            {% if player.spp >= level_cost.3 %}
                                <div class="h5 mb-0 font-weight-bold text-gray-800">
                                    <a href="#" class="btn btn-primary">GET THIS LEVELUP</a>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/teams/prepare_team.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}All Team detail{% endblock %}

{% block content %}
    <h1>Prepare team - <b>{{ team.name }}</b> -- Treasury <b>{{ team.treasury }}</b></h1>
    <br>
    <hr>
    <h3> Extra to buy:</h3>
    <div class="table-responsive">
        <table class="table table-striped table-sm">
            <thead>
            <th>Extra</th>
            <TH>COST</TH>
            <TH>BOUGHT</TH>
            <TH>ACTION</TH>
            </thead>
            <tbody>
            <tr>
                <td>Re Roll</td>
                <td>{{ team.roster_team.re_roll_cost }}</td>
                <td>{{ team.re_roll }}</td>
                <td>
                    <a href="{% url 'teams:buy_re_roll' team.id %}" class="btn btn-primary">ADD</a>
                    <a href="{% url 'teams:remove_re_roll' team.id %}" class="btn btn-primary">REMOVE</a>
                </td>
            </tr>
            <tr>
                <td>Assistant coach</td>
                <td>10000</td>
                <td>{{ team.assistant_coach }}</td>
                <td>
                    <a href="{% url 'teams:buy_assistant_coach' team.id %}" class="btn btn-primary">ADD</a>
                    <a href="{% url 'teams:remove_assistant_coach' team.id %}" class="btn btn-primary">REMOVE</a>
                </td>
            </tr>
            <tr>
                <td>Cheerleader</td>
                <td>10000</td>
                <td>{{ team.cheerleader }}</td>
                <td>
                    <a href="{% url 'teams:buy_cheerleader' team.id %}" class="btn btn-primary">ADD</a>
                    <a href="{% url 'teams:remove_cheerleader' team.id %}" class="btn btn-primary">REMOVE</a>
                </td>
            </tr>
            <tr>
                <td>Extra dedicated fan</td>
                <td>10000</td>
                <td>{{ team.extra_dedicated_fan }}</td>
                <td>
                    <a href="{% url 'teams:buy_extra_fan' team.id %}" class="btn btn-primary">ADD</a>
                    <a href="{% url 'teams:remove_extra_fan' team.id %}" class="btn btn-primary">REMOVE</a>
                </td>
            </tr>
            {% if team.roster_team.apothecary == True %}
                <tr>
                    <td>Apothecary</td>
                    <td>50000</td>
                    <td>
                        {% if team.apothecary %}
                            YES
                        {% else %}
                            NO
                        {% endif %}
                    </td>
                    <td>
                        <a href="{% url 'teams:buy_apothecary' team.id %}" class="btn btn-primary">BUY</a>
                        <a href="{% url 'teams:remove_apothecary' team.id %}" class="btn btn-primary">FIRE</a>
                    </td>
                </tr>
            {% endif %}
            </tbody>
        </table>
    </div>

    <br>
    <hr>
    <h3> Players to buy:</h3>
    <div class="table-responsive">
        <table class="table table-striped table-sm">
            <thead>
            <th>POSITION</th>
            <TH>COST</TH>
            <TH>ACTION</TH>
            </thead>
            <tbody>
            {% for roster_player in roster_players %}
                <tr>
                    <td>{{ roster_player.position }}</td>
                    <td>{{ roster_player.cost }}</td>
                    <td><a href="{% url 'teams:buy_player' team.id %}?roster_player={{ roster_player.id }}"
                           class="btn btn-primary">BUY</a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    <hr>
    <br>
    <h3> Bought players:</h3>
<div class="table-responsive">
        <table class="table table-striped table-sm">
            <thead>
            <th>POSITION</th>
            <TH>COST</TH>
            <TH>ACTION</TH>
            </thead>
            <tbody>
            {% for player in team.players.all %}
                <tr>
                    <td>{{ player.position }}</td>
                    <td>{{ player.cost }}</td>
                    <td><a href="{% url 'teams:fire_player' team.id %}?player={{ player.id }}"
                           class="btn btn-primary">FIRE</a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <br>
    <hr>
    <a href="{% url 'teams:ready_team' team.id %}" class="btn btn-primary">READY TEAM</a>

    <br>
    <hr>
    <br>

{% endblock %}