league/urls.py
from django.urls import path
from . import views

app_name = 'league'

urlpatterns = [
    path('request/new_league', views.request_new_league, name='request_new_league'),
    path('manager/league_i_manage', views.get_league_i_manage, name='league_i_manage'),
    path('manager/league_detail/<int:league_id>', views.get_league_detail, name='league_detail'),
    path('manager/league_user_detail/<int:league_id>', views.get_league_user_detail, name='league_user_detail'),
    path('manager/season_detail/<int:season_id>', views.get_season_detail, name='season_detail'),
    path('manager/season_user_detail/<int:season_id>', views.get_season_user_detail, name='season_user_detail'),
    path('manager/tournament_detail/<int:tournament_id>', views.get_tournament_detail, name='tournament_detail'),
    path('manager/tournament_user_detail/<int:tournament_id>', views.get_tournament_user_detail, name='tournament_user_detail'),
    path('manager/create_season/<int:league_id>', views.create_season, name='create_season'),
    path('manager/create_tournament/<int:season_id>', views.create_tournament, name='create_tournament'),
    path('manager/add_team_to_season/<int:season_id>', views.add_team_to_season, name='add_team_to_season'),
    path('manager/add_team_to_tournament/<int:tournament_id>', views.add_team_to_tournament, name='add_team_to_tournament'),
    path('list', views.get_all_leagues, name='get_all_leagues'),
    path('joined_list', views.get_all_joined_leagues, name='get_all_joined_leagues'),
    path('seasons_joined_list', views.get_all_joined_seasons, name='get_all_joined_seasons'),
    path('tournaments_joined_list', views.get_all_joined_tournaments, name='get_all_joined_tournaments'),
    path('calendar', views.calendar, name='calendar')
]

lpc_py_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('auth', obtain_auth_token),
    path('teams/', include('teams.urls')),
    path('matches/', include('match.urls')),
    path('league/', include('league.urls')),
    path('apiLeague/', include('leagueApi.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
]

match/urls.py
from django.urls import path
from . import views


app_name = 'match'

urlpatterns = [
    path('', views.AllMatchesToPlayListView.as_view(), name='all_matches'),
    path('played', views.AllMatchesPlayedListView.as_view(), name='all_matches_played'),
    path('my_matches/', views.MyMatchesToPlayListView.as_view(), name='my_matches'),
    path('my_matches/played',views. MyMatchesPlayedListView.as_view(), name='my_matches_played'),
    path('close/<int:match_id>/', views.close_match, name='close_match'),
]

teams/urls.py
from django.urls import path
from . import views

app_name = 'teams'

urlpatterns = [
    path('index/', views.index_test, name='index_test'),
    path('', views.AllTeamListView.as_view(), name='all_teams'),
    path('all_ready_teams/', views.AllReadyTeamListView.as_view(), name='all_ready_teams'),
    path('<int:pk>/', views.AllTeamDetail.as_view(), name='all_team_detail'),
    path('my_teams/', views.MyTeamsListView.as_view(), name='my_teams'),
    path('my_retired_teams/', views.MyRetiredTeamsListView.as_view(), name='my_retired_teams'),
    path('my_teams/create', views.get_create_my_team, name='create_my_team'),
    path('my_teams/dismiss/<int:pk>/', views.dismiss_team, name='dismiss_team'),
    path('my_teams/preapre/<int:pk>/', views.prepare_team, name='prepare_team'),
    path('my_teams/ready/<int:pk>/', views.ready_team, name='ready_team'),
    path('my_teams/buy_player/<int:team_id>', views.buy_player, name='buy_player'),
    path('my_teams/fire_player/<int:team_id>', views.fire_player, name='fire_player'),
    path('my_teams/detail/<int:team_id>', views.my_team_detail, name='my_team_detail'),
    path('my_teams/buy_re_roll/<int:team_id>', views.buy_re_roll, name='buy_re_roll'),
    path('my_teams/remove_re_roll/<int:team_id>', views.remove_re_roll, name='remove_re_roll'),
    path('my_teams/buy_assistant_coach/<int:team_id>', views.buy_assistant_coach, name='buy_assistant_coach'),
    path('my_teams/remove_assistant_coach/<int:team_id>', views.remove_assistant_coach, name='remove_assistant_coach'),
    path('my_teams/buy_cheerleader/<int:team_id>', views.buy_cheerleader, name='buy_cheerleader'),
    path('my_teams/remove_cheerleader/<int:team_id>', views.remove_cheerleader, name='remove_cheerleader'),
    path('my_teams/buy_extra_fan/<int:team_id>', views.buy_extra_fan, name='buy_extra_fan'),
    path('my_teams/remove_extra_fan/<int:team_id>', views.remove_extra_fan, name='remove_extra_fan'),
    path('my_teams/buy_apothecary/<int:team_id>', views.buy_apothecary, name='buy_apothecary'),
    path('my_teams/remove_apothecary/<int:team_id>', views.remove_apothecary, name='remove_apothecary'),
    path('my_teams/manage_player/<int:team_id>', views.manage_player, name='manage_player'),
    path('my_teams/manage_player/change_name_number', views.change_player_name_number, name='change_player_name_number'),
    path('my_teams/manage_player/fire_player/<int:team_id>', views.manage_fire_player, name='manage_fire_player'),

    path('my_teams/manage_team/buy_re_roll/<int:team_id>', views.manage_buy_re_roll, name='manage_buy_re_roll'),
    path('my_teams/manage_team/remove_re_roll/<int:team_id>', views.manage_remove_re_roll, name='manage_remove_re_roll'),
    path('my_teams/manage_team/buy_assistant_coach/<int:team_id>', views.manage_buy_assistant_coach,
         name='manage_buy_assistant_coach'),
    path('my_teams/manage_team/remove_assistant_coach/<int:team_id>', views.manage_remove_assistant_coach,
         name='manage_remove_assistant_coach'),
    path('my_teams/manage_team/buy_cheerleader/<int:team_id>', views.manage_buy_cheerleader, name='manage_buy_cheerleader'),
    path('my_teams/manage_team/remove_cheerleader/<int:team_id>', views.manage_remove_cheerleader,
         name='manage_remove_cheerleader'),
    path('my_teams/manage_team/buy_apothecary/<int:team_id>', views.manage_buy_apothecary, name='manage_buy_apothecary'),
    path('my_teams/manage_team/remove_apothecary/<int:team_id>', views.manage_remove_apothecary,
         name='manage_remove_apothecary'),
    path('my_teams/manage_team/buy_player.py/<int:team_id>', views.manage_buy_player, name='manage_buy_player'),
    path('my_teams/manage_team/levelup/<int:player_id>', views.player_level_up, name='player_level_up'),
    path('my_teams/manage_team/levelup/first_random/<int:player_id>', views.random_first_skill, name='random_first_skill'),
    path('my_teams/manage_team/levelup/second_random/<int:player_id>', views.random_second_skill, name='random_second_skill'),
    path('my_teams/manage_team/levelup/choose_first/<int:player_id>', views.select_first_skill, name='select_first_skill'),
    path('my_teams/manage_team/levelup/choose_secondary/<int:player_id>', views.select_second_skill,
         name='select_second_skill'),
    path('my_teams/create_pdf/<int:team_id>', views.render_pdf_view, name='create_pdf'),
    path('my_teams/manage_team/confirm_journeyman/<int:team_id>', views.confirm_journeyman, name='confirm_journeyman')
]

league/models.py
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator
from django.db import models
from django.db.models import Model


class League(models.Model):
    name = models.CharField(max_length=50)
    STATUS_CHOICES = (
        ('CLOSED', 'CLOSED'),
        ('OPEN', 'OPEN'),
    )
    status = models.CharField(max_length=20, choices=STATUS_CHOICES)
    managers = models.ManyToManyField(User, related_name='managers', blank=True)

    def __str__(self):
        return self.name

    def debug(self):
        return 'League {"name": ' + self.name + ',"status": ' + self.status + ',"managers": ' + str(self.managers) + '}'


class Season(models.Model):
    name = models.CharField(max_length=50)
    STATUS_CHOICES = (
        ('CLOSED', 'CLOSED'),
        ('OPEN', 'OPEN'),
    )
    status = models.CharField(max_length=20, choices=STATUS_CHOICES)
    league = models.ForeignKey(League, on_delete=models.CASCADE, related_name='league')

    def __str__(self):
        return self.name

    def debug(self):
        return 'Season {"name": ' + self.name + ',"status": ' + self.status + '}'


class Tournament(models.Model):
    name = models.CharField(max_length=50)
    STATUS_CHOICES = (
        ('CLOSED', 'CLOSED'),
        ('OPEN', 'OPEN'),
    )
    status = models.CharField(max_length=20, choices=STATUS_CHOICES)
    season = models.ForeignKey(Season, on_delete=models.CASCADE, related_name='season')
    team = models.ManyToManyField('teams.Team')

    def __str__(self):
        return self.name

    def debug(self):
        return 'Tournament {"name": ' + self.name + ',"status": ' + self.status + '}'


class TournamentTeamResult(models.Model):
    tournament = models.ForeignKey(Tournament, on_delete=models.CASCADE, related_name='tournament')
    team = models.ForeignKey('teams.Team', on_delete=models.CASCADE, related_name='team')
    win = models.IntegerField(default=0, validators=[MinValueValidator(0)])
    loss = models.IntegerField(default=0, validators=[MinValueValidator(0)])
    tie = models.IntegerField(default=0, validators=[MinValueValidator(0)])
    total_touchdown = models.IntegerField(default=0, validators=[MinValueValidator(0)])
    total_cas = models.IntegerField(default=0, validators=[MinValueValidator(0)])
    league_points = models.IntegerField(default=0, validators=[MinValueValidator(0)])

    def debug(self):
        return 'TournamentResult {"tournament": ' + str(self.tournament) + ', "team":' + str(self.team) + ' }'


class LeagueConfiguration(models.Model):
    league = models.ForeignKey(League, on_delete=models.CASCADE, related_name='league_configuration')
    CONFIGURATION_KEYS = (
        ('EnableFrozen', 'EnableFrozen'),
    )
    key = models.CharField(max_length=20, choices=CONFIGURATION_KEYS)
    value = models.CharField(max_length=100)

league/forms.py
from django import forms


class RequireNewLeagueForm(forms.Form):
    name = forms.CharField(max_length=100)
    author_email = forms.EmailField(max_length=100)


class RequireNewSeasonForm(forms.Form):
    name = forms.CharField(max_length=100)


class RequireNewTournamentForm(forms.Form):
    name = forms.CharField(max_length=100)


class AddTeamForm(forms.Form):
    team = forms.ChoiceField()

templates/league/all_leagues.html
{% extends 'base.html' %}

{% load custom_tags %}

{% block title %}All Leagues{% endblock %}

{% block content %}

    <h1>List of leagues</h1>

    <div>
    List of leagues hosted by portal: if you would join the community, and use us to manage your league,
        use the <a href="{% url 'league:request_new_league' %}">ask for a league procedure</a>
    </div>
    <br>

    <div class="row">
        <div class="col-xl-12 col-md-6 mb-4">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h3 class="m-0 font-weight-bold text-primary">{{ leagues_list_title }}</h3>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="longDataTable">
                            <thead>
                            <th>Leagues name</th>
                            <th>Seasons</th>
                            <th>Tournaments</th>
                            <th>Teams</th>
                            <th>Status</th>
                            </thead>
                            <tbody>
                            {% for league in leagues_dto %}
                                <tr>
                                    <td>
                                        <a href="{% url 'league:league_detail' league.league.id %}">
                                            {{ league.league.name }}
                                        </a>
                                    </td>
                                    <td>{{ league.seasons_count }}</td>
                                    <td>{{ league.tournaments_count }}</td>
                                    <td>{{ league.teams_count }}</td>
                                    <td>{{ league.league_status }}</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/league/create_new_season.html
{% extends 'base.html' %}

{% block title %}Request new Season{% endblock %}

{% block content %}

    <h1>Request for a new Season for <b>{{ league.name }}</b> league</h1>
    <br>

    <form method="post" novalidate>
        {% csrf_token %}

        <div class="row">
            <div class="col-xl-12 col-md-6 mb-4">
                <div class="card shadow mb-4">
                    <div class="card-header py-3">
                        <h3 class="m-0 font-weight-bold text-primary">Fill information to create a new season</h3>
                    </div>
                    <div class="card-body">
                        <div class="form-group">
                            Season name *
                            <input type="text" id="id_name" name="name" class="form-control form-control-user">
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <br>

        <button type="submit" class="btn btn-primary">Create season</button>

    </form>

{% endblock %}

templates/league/league_detail.html
{% extends 'base.html' %}

{% load custom_tags %}

{% block title %}League I Manage{% endblock %}

{% block content %}

    <!-- FIRST ROW -->
    <div class="row">
        <!-- Admin card -->
        <div class="col-xl-4 col-md-6 mb-4">
            <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                League admin
                            </div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">
                                <br>
                                <ul>
                                    {% for manager in league.managers.all %}
                                        <li>{{ manager.username }}</li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Number of teams -->
        <div class="col-xl-4 col-md-6 mb-4">
            <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                Number of teams
                            </div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">{{ number_of_teams }}</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-comments fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Number of tournaments -->
        <div class="col-xl-4 col-md-6 mb-4">
            <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                Number of tournaments
                            </div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">Number of tournaments</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-comments fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Second ROW: Seasons list -->
    <div class="row">
        <div class="col-xl-12 col-md-6 mb-4">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h3 class="m-0 font-weight-bold text-primary">Seasons List</h3>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="longDataTable">
                            <thead>
                            <th>Name</th>
                            <th>Status</th>
                            </thead>
                            <tbody>
                            {% for season in league_seasons %}
                                <tr>
                                    <td>
                                        <a href="{% url 'league:season_detail' season.id %}">
                                            {{ season.name }}
                                        </a>
                                    </td>
                                    <td>{{ season.status }}</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <br>
    <a href="{% url 'league:league_i_manage' %}" class="btn btn-primary">Back</a>
    <a href="{% url 'league:create_season' league.id %}" class="btn btn-primary">Create season</a>

{% endblock %}

templates/league/season_detail.html
{% extends 'base.html' %}

{% load custom_tags %}

{% block title %}League I Manage{% endblock %}

{% block content %}

    <!-- FIRST ROW -->
    <div class="row">
        <!-- Admin card -->
        <div class="col-xl-4 col-md-6 mb-4">
            <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                Best team for each tournament
                            </div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">
                                <br>
                                <ul>
                                    <li>Nome team (tournament)</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Number of teams -->
        <div class="col-xl-4 col-md-6 mb-4">
            <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                Number of teams
                            </div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">{{ number_of_teams }}</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-comments fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Number of tournaments -->
        <div class="col-xl-4 col-md-6 mb-4">
            <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                Best player for each tournament
                            </div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">Best player</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-comments fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Second ROW: Seasons list -->
    <div class="row">
        <div class="col-xl-12 col-md-6 mb-4">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h3 class="m-0 font-weight-bold text-primary">Tournament List</h3>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="longDataTable">
                            <thead>
                            <th>Name</th>
                            <th>Status</th>
                            </thead>
                            <tbody>
                            {% for tournament in season_tournaments %}
                                <tr>
                                    <td>
                                        <a href="{% url 'league:tournament_detail' tournament.id %}">
                                            {{ tournament.name }}
                                        </a>
                                    </td>
                                    <td>{{ tournament.status }}</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Third ROW: teams list -->
    <div class="row">
        <div class="col-xl-12 col-md-6 mb-4">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h3 class="m-0 font-weight-bold text-primary">Teams List</h3>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="longDataTable">
                            <thead>
                            <th>Name</th>
                            <th>Coach</th>
                            </thead>
                            <tbody>
                            {% for team in all_teams %}
                                <tr>
                                    <td>
                                        <a href="#">
                                            {{ team.name }}
                                        </a>
                                    </td>
                                    <td>{{ team.coach }}</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <br>
    <a href="{% url 'league:league_detail' league.id %}" class="btn btn-primary">Back</a>
    <a href="{% url 'league:create_tournament' season.id %}" class="btn btn-primary">Create tournament</a>
    <a href="{% url 'league:add_team_to_season' season.id %}" class="btn btn-primary">Add team</a>

{% endblock %}

templates/league/tournament_detail.html
{% extends 'base.html' %}

{% load custom_tags %}

{% block title %}League I Manage{% endblock %}

{% block content %}

    <!-- FIRST ROW -->
    <div class="row">
        <!-- Admin card -->
        <div class="col-xl-4 col-md-6 mb-4">
            <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                Best team for each tournament
                            </div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">
                                <br>
                                <ul>
                                    <li>Nome team (tournament)</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Number of teams -->
        <div class="col-xl-4 col-md-6 mb-4">
            <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                Number of teams
                            </div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">{{ number_of_teams }}</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-comments fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Number of tournaments -->
        <div class="col-xl-4 col-md-6 mb-4">
            <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                Best player for each tournament
                            </div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">Best player</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-comments fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Third ROW: teams list -->
    <div class="row">
        <div class="col-xl-12 col-md-6 mb-4">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h3 class="m-0 font-weight-bold text-primary">Teams List</h3>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="longDataTable">
                            <thead>
                            <th>Name</th>
                            <th>Coach</th>
                            <th>WIN</th>
                            <th>TIE</th>
                            <th>LOSS</th>
                            <th>CAS</th>
                            <th>TD</th>
                            <th>POINT</th>
                            </thead>
                            <tbody>
                            {% for result in all_results %}
                                <tr>
                                    <td>
                                        <a href="#">
                                            {{ result.team.name }}
                                        </a>
                                    </td>
                                    <td>{{ result.team.coach }}</td>
                                    <td>{{ result.win }}</td>
                                    <td>{{ result.tie }}</td>
                                    <td>{{ result.loss }}</td>
                                    <td>{{ result.total_cas }}</td>
                                    <td>{{ result.total_touchdown }}</td>
                                    <td>{{ result.league_points }}</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Third ROW: teams list -->
    <div class="row">
        <div class="col-xl-12 col-md-6 mb-4">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h3 class="m-0 font-weight-bold text-primary">Match List</h3>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="longDataTable">
                            <thead>
                            <th>Team A</th>
                            <th>Team B</th>
                            <th>From Date</th>
                            <th>To Date</th>
                            <th>Action</th>
                            </thead>
                            <tbody>
                            {% for match in all_matches %}
                                <tr>
                                    <td>
                                        <a href="{% url 'teams:all_team_detail' match.first_team.id %}">{{ match.first_team }}</a>
                                        - [CTV {{ obj.first_team.current_team_value }}]
                                    </td>
                                    <td>
                                        <a href="{% url 'teams:all_team_detail' match.second_team.id %}">{{ match.second_team }}</a>
                                        - [CTV {{ obj.second_team.current_team_value }}]
                                    </td>
                                    <td>{{ match.match_date_from }}</td>
                                    <td>{{ match.match_date_to }}</td>
                                    <td>
                                        {% if match.played %}
                                            PLAYED
                                        {% else %}
                                            <a href="{% url 'match:close_match' match.id %}" class="btn btn-primary">CLOSE</a>
                                        {% endif %}
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <br>
    <a href="{% url 'league:season_detail' season.id %}" class="btn btn-primary">Back</a>
    <a href="{% url 'league:add_team_to_tournament' tournament.id %}" class="btn btn-primary">Add team</a>

{% endblock %}